# Generated by Django 4.2 on 2023-06-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='table_classes',
            name='attendees',
        ),
        migrations.AlterField(
            model_name='table_classes',
            name='class_day',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday')], default='monday', max_length=9),
        ),
        migrations.AddField(
            model_name='table_classes',
            name='attendees',
            field=models.ManyToManyField(to='sas.attendee'),
        ),
    ]
