# Generated by Django 4.2 on 2023-07-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dininghall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='live_bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('served_time', models.TimeField()),
                ('depart_time', models.TimeField()),
            ],
        ),
    ]
