# Generated by Django 4.2 on 2023-05-31 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dininghall', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table_staff_information',
        ),
    ]
