# Generated by Django 4.2 on 2023-06-03 09:42

from django.db import migrations
from django.db import migrations

def populate_table_menu(apps, schema_editor):
    table_menu = apps.get_model('dininghall', 'table_menu')
    table_menu.objects.create(date='2023-06-03', session='Breakfast', menu='Nasi Goreng, Telur, Susu, Pisang', limit=100, available=100)
    table_menu.objects.create(date='2023-06-03', session='Lunch', menu='Nasi, Ayam Asam Manis, Semangka', limit=100, available=100)
    table_menu.objects.create(date='2023-06-03', session='Dinner', menu='Nasi, Fuyunghai, Pisang', limit=100, available=100)

def populate_table_time(apps, schema_editor):
    table_time = apps.get_model('dininghall', 'table_time')
    table_time.objects.create(time='11:00')
    table_time.objects.create(time='11:30')
    table_time.objects.create(time='12:00')
    table_time.objects.create(time='12:30')
    table_time.objects.create(time='13:00')
    table_time.objects.create(time='13:30')

class Migration(migrations.Migration):

    dependencies = [
        ('dininghall', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_table_menu),
        migrations.RunPython(populate_table_time),
    ]
