# Generated by Django 4.2 on 2023-06-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dininghall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table_menu',
            old_name='vacancy',
            new_name='limit',
        ),
        migrations.RemoveField(
            model_name='table_booking_dininghall',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='table_booking_dininghall',
            name='available',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='table_menu',
            name='available',
            field=models.IntegerField(null=True),
        ),
    ]
