# Generated by Django 4.2 on 2023-07-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dininghall', '0002_live_bookings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='live_bookings',
            new_name='table_live_bookings',
        ),
    ]
