# Generated by Django 4.2 on 2023-05-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('dininghall', '0002_table_booking_dininghall_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_booking_dininghall',
            name='students_nim',
            field=models.ManyToManyField(to='students.table_students_information'),
        ),
    ]
