# Generated by Django 4.2 on 2023-05-31 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dininghall', '0002_delete_table_staff_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_booking_dininghall',
            name='students_nim',
        ),
        migrations.AddField(
            model_name='table_booking_dininghall',
            name='students_nim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
