# Generated by Django 4.2 on 2023-05-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dininghall', '0003_alter_table_booking_dininghall_students_nim'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_staff_information',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
