# Generated by Django 4.2 on 2023-07-10 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dininghall', '0004_rename_table_live_bookings_table_live_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_live_booking',
            name='bookings_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dininghall.table_booking_dininghall'),
        ),
    ]
