# Generated by Django 4.2 on 2023-05-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dininghall', '0004_table_staff_information_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_booking_dininghall',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='table_menu',
            name='vacancy',
            field=models.IntegerField(null=True),
        ),
    ]
