# Generated by Django 4.2 on 2023-05-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dininghall', '0005_remove_table_booking_dininghall_vacancy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_booking_dininghall',
            name='vacancy',
            field=models.IntegerField(default=0),
        ),
    ]
