# Generated by Django 4.2 on 2023-07-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table_students_information',
            fields=[
                ('nim', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('study_program', models.CharField(max_length=10)),
                ('batch_year', models.SmallIntegerField()),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
