# Generated by Django 4.2 on 2023-05-29 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table_students_information',
            fields=[
                ('nim', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('study_program', models.CharField(max_length=10)),
                ('batch_year', models.SmallIntegerField()),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='table_classes',
            fields=[
                ('class_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('class_name', models.TextField()),
                ('class_date', models.DateField()),
                ('class_start', models.IntegerField()),
                ('class_end', models.IntegerField()),
                ('attendes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.table_students_information')),
            ],
        ),
    ]
