# Generated by Django 4.2 on 2023-06-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table_classes',
        ),
    ]
