# Generated by Django 4.2 on 2023-05-16 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_table_students_information_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_class',
            fields=[
                ('class_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('class_name', models.TextField()),
                ('class_date', models.DateField()),
                ('class_start', models.IntegerField()),
                ('class_end', models.IntegerField()),
                ('attendes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.table_students_information')),
            ],
        ),
    ]
