# Generated by Django 4.2 on 2023-05-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_table_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='table_class',
            new_name='table_classes',
        ),
    ]
